name: 'Sending Status Notification to Slack (Composite)'
description: "Sends the status of the GitHub Action to the"

inputs:
  github-token:
    description: 'The Github Token to authenticate with with GitHub API'
    required: true
  github-username:
    description: 'The GitHub username of the employee to look up'
    required: true
  slack-token:
    description: 'The organizational Slack access token'
    required: true

runs:
  using: composite
  steps:
    - uses: './get-employee-js-action'
      id: 'get-employee-js'
      with:
        github-username: ${{ inputs.github-username }}
        github-token: ${{ inputs.github-token }}
        slack-token: ${{ inputs.slack-token }}

    - uses: './get-employee-docker-action'
      id: 'get-employee-docker'
      with:
        github-username: ${{ inputs.github-username }}
        github-token: ${{ inputs.github-token }}
        slack-token: ${{ inputs.slack-token }}

    - run: |
        echo "::error::slack user IDs do not match from JS ans Docker"  
        exit 1
      if: steps.get-employee-js.outputs.slack-user-id != steps.get-employee-docker.outputs.slack-user-id
      shell: sh

    - name: Send a saved artifact to a Slack workflow
      uses: slackapi/slack-github-action@v2.0.0
      if: steps.get-employee-js.outputs.slack-user-id != steps.get-employee-docker.outputs.slack-user-id

      with:
        channel-id: ${{ steps.get-employee-js.outputs.slack-user-id }}
        slack-message: "GitHub build results : {{ job.status }}\n${{ github.event.pull_request.html.url || github.event.head_commit.url }}"
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}